### ISSUE TITLE
ran out of wall time

### ISSUE THREAD

**Issue by kitchell** [soichih/sca-service-neuro-tracking#5]
I submitted this app for an hcp subject and it ran out of wall time, but that does not make sense as walltime is 12 hours and it is only making 3 tcks. it looks like the default is set to make 500000 streamlines per track. Should this be lower maybe?

**Comment by soichih** [comment]
This app stopped working recently. I believe the default 500k should work, but maybe I am wrong. I will investigate.

**Comment by soichih** [comment]
I've run it again with the default 500k stream and it timed out. 

I've reduced the ppn from 16 to 8  about a month ago - so that the same submit.pbs can be used on both Karst and carbonate without wasting the cpu slot on carbonate. I might need to bring it back to 16.. but I am not sure. (UPDATE: ppn=16 didn't cure it. I've put it back to ppn=8)

I am also seeing a whole bunch of following message in the log

```
csdeconv: failed to converge
```

According to this [doc](http://jdtournier.github.io/mrtrix-0.2/faq.html#converge)

> csdeconv will produce one such message per voxel where the CSD fails to converge. It is not unusual to get a dozen or so such messages per data set when performing a super-resolved reconstruction (see above). The voxels affected are typically not in white matter, so these failures usually won't affect any subsequent tractography.

> However, if you are getting a lot of these messages, you may need to check that the CSD images are suitable. They can be loaded directly into MRview: the voxels that failed to converge will appear black. If these messages do signal a real problem, you should try to perform the CSD using a lower value of lmax. In particular, you will usually not get any such messages when performing non-super-resolved CSD (see above).

I am rerunning it again with lmax=8 (I think it auto computes to lmax=10).

**Comment by soichih** [comment]
I can't seems to get this app to work past "generating DT_STREAM". It get stuck on following line

>  time streamtrack -quiet SD_STREAM lmax.mif output.SD_STREAM.tck -seed wm.mif -mask wm.mif -grad $BGRAD -number $NUMFIBERS -maxnum $MAXNUMFIBERSATTEMPTED

I've tried with different ppn (8 or 16), on different clusters (Karst, Carbonate), on different datasets (NKI, HCP) with different track count (as little as 500) but it all gets suck on DT_STREAM.

I will see if I can recreate on a small script.

**Comment by francopestilli** [comment]
@soichih failed to converge normally happens when data SNR is low, for example outside of the brain or in ventricles, or with really bad data. I might need to look at the files you generated with the apps. Where are they can I get access pls?

**Comment by soichih** [comment]
@francopestilli I can run ensemble tracking just fine, and this issue happens on pretty much all HCP and NKI subjects.

I've posted the partial output from one of the task that failed here
> /N/dc2/projects/lifebid/hayashis/forfranco/59e4b884fed4660034b648b3.59e9f5affed4660034b64b31.tar.gz

I see absolutely nothing useful generated from the streamtrack command,, however. I am setting -quiet so that might be expected. 

Here is the main script
> https://github.com/brain-life/app-tracking/blob/master/submit.pbs

 You can try recreating it by just grabbing any NKI subject on Brain-Life and running app-tracking app.

**Comment by soichih** [comment]
I've fixed this issue - using vistasoft's function to generate grad.b.
